language: python
python:
    - "3.4"
env:
    matrix:
        - TOXENV=py34
        - TOXENV=py33
        - TOXENV=flake8
        - TOXENV=pylint
        - TOXENV=tests
install: "pip install tox"
script: tox
notifications:
    hipchat:
        rooms:
            secure: AKfufy7lL5Ea3czbc6hSZ7vqnIGIHCcphj8xNuqQbZnYUw3NnfalSnqPQgAEOmuP5ysTn/iN0B8mEeBbr5Jjf6vHLBrSfuuid/lKu0z8bOJ+9Dv5dR3zkPl7Af4nIWoxDcvldMUHlOQ1Ce6TH0Tvb7/mWDwqOA1K5Lq8ZOQhZ3A=
